### ISSUE TITLE
Release to the Central Repository

### ISSUE THREAD

**Issue by raner** [Jyskebank/enunciate-openapi#1]
I'd love to use enunciate-openapi, but right now I would have to splice it into my build process in a rather unconventional way. Assuming that this project is at least to some degree production-ready, it would be nice if you could put a release on [the Central Repository](http://central.sonatype.org/), so that this plugin can be easily consumed in Maven and Gradle builds (see instructions [here](http://central.sonatype.org/pages/ossrh-guide.html)).

**Comment by jskovjyskebankdk** [comment]
Indeed. And I will. At some time.
But I do not have the time available at the moment. I need to sort out how to handle the security of the signing.

**Comment by raner** [comment]
Thanks for the prompt response, Jesper. If it is any help at all, the key generation procedure is described [here](http://central.sonatype.org/pages/working-with-pgp-signatures.html), and the signing can be easily done with the `maven-gpg-plugin`.

**Comment by jskovjyskebankdk** [comment]
The module is available on Central now

**Comment by raner** [comment]
👍 Awesome, I just saw that this was completed. Thanks for releasing this to the Central Repo and making it available to other developers!
