### ISSUE TITLE
RequestBody for String input renders as schema string/binary

### ISSUE THREAD

**Issue by jskovjyskebankdk** [Jyskebank/enunciate-openapi#10]
It should just be plain string.

**Comment by pnest** [comment]
Looks like `@RequestBody` always is rendered as string/binary even when there is an dto in parameter

**Comment by jskovjyskebankdk** [comment]
I think I have a local fix for this that I just need to push out to this repository. I will see if I can find time to do it this week.

**Comment by jskovjyskebankdk** [comment]
This was actually fixed in c13f355f2850712b1818db89c37de5cafb4b23d3, released in 1.0.8.

@pnest if you see something else, I would like to see how your resource+DTO is annotated. My unit test covers request body for XML/DTO, InputStream, and String. So if it does not work for you, I must be missing something.

**Comment by jskovjyskebankdk** [comment]
Oooh. I take that back.

Sorry, the unit test was disabled. I never got around to fixing it. Will do now.

**Comment by jskovjyskebankdk** [comment]
Should be fixed now.
