### ISSUE TITLE
@Consumes and @Produces do not support multiple media type entries

### ISSUE THREAD

**Issue by bkratz** [Jyskebank/enunciate-openapi#30]
Given following Resource code with `@Produces` having multiple media type entries:
```java
@ResourceGroup("Resource group text")
@Path("/path/{pathArg}")
public class DataResource {
	@GET
	@Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
	@StatusCodes({
			@ResponseCode(code = 200, condition = "OK", type=@TypeHint(DataDTO.class)),
			@ResponseCode(code = 400, condition = "Bad request")
	})
	public Response get(@PathParam("pathArg") String pathArg) {
		return Response.ok(new DataDTO()).build();
	}
}
```

 the generated openapi.yaml is expected to be:
```yaml
openapi: 3.0.0
...
      responses:
        "200":
          description: "OK"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/json_DataDTO"
            "application/xml":
              schema:
                $ref: "#/components/schemas/xml_ns0_dataDTO"
        "400":
          description: "Bad request"
 
components:
...
```

but is currently:
```yaml
openapi: 3.0.0
...
      responses:
        "200":
          description: "OK"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/json_DataDTO"
        "400":
          description: "Bad request"
 
components:
...
```

The same issue applies to `@Consumes` containing multiple media type entries.

I have already analysed the problem. It seems that the generator selects the "best" high quality media type and ignores the others. This does not conform with the idea of openAPI because openAPI does not have the concept of weighing media types.

I will prepare a PR for this issue.

**Comment by jskovjyskebankdk** [comment]
Nice!

**Comment by bkratz** [comment]
Would be cool, if you could accept this PR #31 and release a new version of this module. Thx.

**Comment by jskovjyskebankdk** [comment]
https://github.com/Jyskebank/enunciate-openapi/releases/tag/1.1.5
And https://repo1.maven.org/maven2/dk/jyskebank/tooling/enunciate/enunciate-openapi/1.1.5/

Maven Central index is not updated yet, but you should be able to pull the artifacts.
