### ISSUE TITLE
Enunciate openapi module support for JAXBElement

### ISSUE THREAD

**Issue by sakthisunda** [Jyskebank/enunciate-openapi#7]
Enunciate version 11.x
JAX-RS web api
enunciate-openapi

When I run enunciate on my Java package JAXBElements are not getting into final openapi.yaml

Method signature: public **JAXBElement\<getSelectorExtensions>**(

For the above signature, the wrong response model is returned.
**Response Model: String**

Screenshot attached ( from Swagger editor )

![jaxbelement support](https://user-images.githubusercontent.com/5530442/43349237-53d61c12-91b3-11e8-8231-7ed23921e8cb.png)

**Comment by jskovjyskebankdk** [comment]
Sorry, I have no idea of what this means.
If it is still relevant, please re-open with a full resource method example, and the OpenSpec output you would expect.

**Comment by sakthisunda** [comment]
I expected it to support generic type JAXBElement<type>. That is all. Here it is returned as empty String. I expect XMLElement.

**Comment by jskovjyskebankdk** [comment]
I have no personal experience with JAXBElement.
If you want me to look into it, I need a concrete code example, and what output you expect.
